name: Deploy to Server

on:
  push:
    branches:
      - dev         # Для backend
      - develop # Для frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          path: backend
          ref: dev

      - name: Checkout frontend repo
        uses: actions/checkout@v3
        with:
          repository: funkjus/stockui
          path: frontend
          ref: develop

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/warehouse-deploy
            ./deploy.sh
